### ISSUE TITLE
esmbot issue 7/15/20

### ISSUE THREAD

**Issue by f343443** [TheEssem/esmBot#9] opened 2020-07-16 06:43 UTC
[error.txt](https://github.com/TheEssem/esmBot/files/4929735/error.txt)
but cannot process any image with the &caption command (possibly more)

**Comment by TheEssem** [comment] 2020-07-16 14:15
duplicate of #5, should be fixed somewhat in the next update

**Closed by TheEssem** 2020-07-16 14:15 UTC
